AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ES:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::000000000000:role/echosistant_execution'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Environment:
        Variables:
          STurl: >-
            https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/5a774ca2-3319-4b6d-bfdb-000000000000/
          STtoken: 615181ae-948f-44de-b0b5-000000000000
          profileData: ''
