AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ES:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::016139245837:role/echosistant_execution'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Environment:
        Variables:
          STurl: >-
            https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/16bf4a6d-f99c-4732-b3ea-000000000000/
          allESSettings: empty
          STtoken: 015f9d48-f54d-4e11-be78-000000000000
